[build]
  command = "npm run build"
  publish = "dist"
  node_version = "18"

[dev]
  command = "vite"
  port = 5173
  targetPort = 5173

# Redirect all routes to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers for production
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https://*.supabase.co wss://*.supabase.co; frame-src 'none';"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Don't cache the main HTML file
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache"

# Optimize for mobile performance
[[headers]]
  for = "/*"
  [headers.values]
    Accept-CH = "DPR, Viewport-Width, Width"